# Generated by Django 3.1.6 on 2021-03-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities_details', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Canceled'), ('R', 'Rejected'), ('W', 'Waiting')], default='W', max_length=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateField()),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='entities_details.serviceschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_appointments', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Services Appointments',
            },
        ),
        migrations.CreateModel(
            name='RoomAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Canceled'), ('R', 'Rejected'), ('W', 'Waiting')], default='W', max_length=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateField()),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='entities_details.roomschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_appointments', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Rooms Appointments',
            },
        ),
        migrations.CreateModel(
            name='ClinicAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Canceled'), ('R', 'Rejected'), ('W', 'Waiting')], default='W', max_length=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateField()),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='entities_details.clinicschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_appointments', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Clinics Appointments',
            },
        ),
        migrations.AddConstraint(
            model_name='serviceappointment',
            constraint=models.UniqueConstraint(fields=('user', 'schedule', 'appointment_date'), name='unique_service_appointment'),
        ),
        migrations.AddConstraint(
            model_name='roomappointment',
            constraint=models.UniqueConstraint(fields=('user', 'schedule', 'appointment_date'), name='unique_room_appointment'),
        ),
        migrations.AddConstraint(
            model_name='clinicappointment',
            constraint=models.UniqueConstraint(fields=('user', 'schedule', 'appointment_date'), name='unique_clinic_appointment'),
        ),
    ]
