# Generated by Django 3.2 on 2021-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/users/', verbose_name='photo'),
        ),
    ]
