# Generated by Django 3.2 on 2021-04-15 21:12

from django.db import migrations, models
import treat_min.entities.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to=treat_min.entities.models.image_update, verbose_name='photo'),
        ),
    ]
