# Generated by Django 3.2 on 2021-04-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(default='1999-09-09', verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='lostpassword',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is verified'),
        ),
    ]
