# Generated by Django 3.2 on 2021-04-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210419_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
