# Generated by Django 3.2 on 2021-04-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities_details', '0002_alter_roomdetail_options'),
        ('user_appointments', '0002_auto_20210419_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicappointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='entities_details.clinicschedule', verbose_name='schedule'),
        ),
        migrations.AlterField(
            model_name='roomappointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='entities_details.roomschedule', verbose_name='schedule'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='entities_details.serviceschedule', verbose_name='schedule'),
        ),
    ]
