# Generated by Django 3.1.6 on 2021-03-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treat_min', '0004_auto_20210319_2337'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladmin',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treat_min.hospital'),
        ),
    ]
