# Generated by Django 3.1.6 on 2021-03-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hospitaladmin',
            options={'verbose_name_plural': 'Hospitals Admins'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='groups',
            field=models.ForeignKey(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='phone'),
        ),
    ]
