# Generated by Django 3.1.6 on 2021-03-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unverifieduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifieduser',
            name='code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
