# Generated by Django 3.1.6 on 2021-03-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210327_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
