# Generated by Django 3.1.6 on 2021-04-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_auto_20210331_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='groups',
            field=models.ForeignKey(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='auth.group', verbose_name='groups'),
        ),
    ]
