# Generated by Django 3.1.5 on 2021-04-05 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20210405_0237'),
        ('accounts', '0004_auto_20210404_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('code', models.PositiveSmallIntegerField(verbose_name='code')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is_verified')),
            ],
            options={
                'verbose_name': 'lost password',
                'verbose_name_plural': 'Lost Passwords',
            },
        ),
        migrations.AlterModelOptions(
            name='abstractuser',
            options={'verbose_name': 'abstract user', 'verbose_name_plural': 'Abstract Users'},
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='hospitaladmin',
            options={'verbose_name': 'hospital admin', 'verbose_name_plural': 'Hospitals Admins'},
        ),
        migrations.AlterModelOptions(
            name='pendinguser',
            options={'verbose_name': 'pending user', 'verbose_name_plural': 'Pending Users'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_joined'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active,\nUnselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='entities.hospital', verbose_name='hospital'),
        ),
        migrations.AlterField(
            model_name='hospitaladmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='code',
            field=models.PositiveSmallIntegerField(verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is_verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/users/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
