# Generated by Django 3.1.6 on 2021-03-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_unverifieduser_is_verified'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnverifiedUser',
            new_name='PendingUser',
        ),
    ]
