# Generated by Django 3.1.6 on 2021-03-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(max_length=250)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.servicedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Services Reviews',
            },
        ),
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Canceled'), ('R', 'Rejected'), ('W', 'Waiting')], default='W', max_length=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.serviceschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Services Appointments',
            },
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(max_length=250)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.roomdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Rooms Reviews',
            },
        ),
        migrations.CreateModel(
            name='RoomAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Canceled'), ('R', 'Rejected'), ('W', 'Waiting')], default='W', max_length=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.roomschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Rooms Appointments',
            },
        ),
        migrations.CreateModel(
            name='ClinicReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(max_length=250)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.clinicdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Clinics Reviews',
            },
        ),
        migrations.CreateModel(
            name='ClinicAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Canceled'), ('R', 'Rejected'), ('W', 'Waiting')], default='W', max_length=1)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('appointment_date', models.DateField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.clinicschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Clinics Appointments',
            },
        ),
    ]
