# Generated by Django 3.1.6 on 2021-03-19 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treat_min', '0004_auto_20210319_2337'),
        ('user_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicappointment',
            options={'ordering': ['booking_date']},
        ),
        migrations.AlterModelOptions(
            name='roomappointment',
            options={'ordering': ['booking_date']},
        ),
        migrations.AlterModelOptions(
            name='serviceappointment',
            options={'ordering': ['booking_date']},
        ),
        migrations.AlterField(
            model_name='clinicappointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clinicappointment',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clinicappointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treat_min.clinicschedule'),
        ),
        migrations.AlterField(
            model_name='roomappointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roomappointment',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomappointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treat_min.roomschedule'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treat_min.serviceschedule'),
        ),
    ]
