# Generated by Django 3.1.6 on 2021-03-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicreview',
            name='review',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='review',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='review',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
