# Generated by Django 3.1.6 on 2021-03-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20210322_0941'),
        ('user_actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicappointment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.clinicschedule'),
        ),
        migrations.AlterField(
            model_name='roomappointment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.roomschedule'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.serviceschedule'),
        ),
    ]
