# Generated by Django 3.1.6 on 2021-03-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=50)),
                ('rating_total', models.PositiveIntegerField(default=0)),
                ('rating_users', models.PositiveSmallIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='entities.clinic')),
            ],
            options={
                'verbose_name_plural': 'Clinics Details',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/doctors/')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='entities.clinic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/hospitals/')),
                ('clinics', models.ManyToManyField(related_name='hospitals', through='entities.ClinicDetail', to='entities.Clinic')),
                ('doctors', models.ManyToManyField(related_name='hospitals', through='entities.ClinicDetail', to='entities.Doctor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=50)),
                ('rating_total', models.PositiveIntegerField(default=0)),
                ('rating_users', models.PositiveSmallIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms_details', to='entities.hospital')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='entities.room')),
            ],
            options={
                'verbose_name_plural': 'Rooms Details',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=50)),
                ('rating_total', models.PositiveIntegerField(default=0)),
                ('rating_users', models.PositiveSmallIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services_details', to='entities.hospital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='entities.service')),
            ],
            options={
                'verbose_name_plural': 'Services Details',
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='entities.servicedetail')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='entities.roomdetail')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='rooms',
            field=models.ManyToManyField(related_name='hospitals', through='entities.RoomDetail', to='entities.Room'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(related_name='hospitals', through='entities.ServiceDetail', to='entities.Service'),
        ),
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='entities.clinicdetail')),
            ],
        ),
        migrations.AddField(
            model_name='clinicdetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_details', to='entities.doctor'),
        ),
        migrations.AddField(
            model_name='clinicdetail',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clinics_details', to='entities.hospital'),
        ),
        migrations.AddConstraint(
            model_name='serviceschedule',
            constraint=models.UniqueConstraint(fields=('service', 'day', 'start', 'end'), name='unique_service_schedule'),
        ),
        migrations.AddConstraint(
            model_name='servicedetail',
            constraint=models.UniqueConstraint(fields=('hospital', 'service', 'price'), name='unique_service_detail'),
        ),
        migrations.AddConstraint(
            model_name='roomschedule',
            constraint=models.UniqueConstraint(fields=('room', 'day', 'start', 'end'), name='unique_room_schedule'),
        ),
        migrations.AddConstraint(
            model_name='roomdetail',
            constraint=models.UniqueConstraint(fields=('hospital', 'room', 'price'), name='unique_room_detail'),
        ),
        migrations.AddConstraint(
            model_name='clinicschedule',
            constraint=models.UniqueConstraint(fields=('clinic', 'day', 'start', 'end'), name='unique_clinic_schedule'),
        ),
        migrations.AddConstraint(
            model_name='clinicdetail',
            constraint=models.UniqueConstraint(fields=('hospital', 'doctor', 'price'), name='unique_clinic_detail'),
        ),
    ]
