# Generated by Django 3.1.6 on 2021-03-31 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('entities_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='clinics',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ClinicDetail', to='entities.Clinic'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ClinicDetail', to='entities.Doctor'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='rooms',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.RoomDetail', to='entities.Room'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ServiceDetail', to='entities.Service'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='entities.clinic'),
        ),
    ]
