# Generated by Django 3.1.6 on 2021-04-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20210331_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='doctors', to='entities.clinic'),
        ),
    ]
