# Generated by Django 3.1.5 on 2021-04-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities_details', '0001_initial'),
        ('entities', '0005_auto_20210405_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['name'], 'verbose_name': 'clinic', 'verbose_name_plural': 'Clinics'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name'], 'verbose_name': 'doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name'], 'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/doctors/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='entities.clinic', verbose_name='speciality'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='clinics',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ClinicDetail', to='entities.Clinic', verbose_name='clinics'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ClinicDetail', to='entities.Doctor', verbose_name='doctors'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/hospitals/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='rooms',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.RoomDetail', to='entities.Room', verbose_name='rooms'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ServiceDetail', to='entities.Service', verbose_name='services'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
    ]
