# Generated by Django 3.1.6 on 2021-02-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treat_min', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicschedule',
            name='day',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='time_to',
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='fri_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='fri_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='mon_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='mon_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='sat_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='sat_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='sun_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='sun_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='thu_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='thu_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='tue_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='tue_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='wed_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='wed_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
