# Generated by Django 3.1.6 on 2021-02-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treat_min', '0002_auto_20210219_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicschedule',
            name='rating_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='rating_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomschedule',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='rating_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceschedule',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
