# Generated by Django 3.1.6 on 2021-03-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treat_min', '0003_auto_20210318_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomappointment',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='roomappointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='user',
        ),
        migrations.DeleteModel(
            name='ClinicAppointment',
        ),
        migrations.DeleteModel(
            name='RoomAppointment',
        ),
        migrations.DeleteModel(
            name='ServiceAppointment',
        ),
    ]
