# Generated by Django 3.1.6 on 2021-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reviews', '0002_auto_20210404_2104'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clinicreview',
            constraint=models.UniqueConstraint(fields=('user', 'clinic'), name='unique_clinic_review'),
        ),
        migrations.AddConstraint(
            model_name='roomreview',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_room_review'),
        ),
        migrations.AddConstraint(
            model_name='servicereview',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_service_review'),
        ),
    ]
