# Generated by Django 3.1.6 on 2021-04-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reviews', '0003_auto_20210404_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicreview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
