# Generated by Django 3.1.5 on 2021-04-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210405_0741'),
        ('entities_details', '0002_auto_20210405_0741'),
        ('user_reviews', '0004_auto_20210405_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicreview',
            options={'verbose_name': 'clinic review', 'verbose_name_plural': 'Clinics Reviews'},
        ),
        migrations.AlterModelOptions(
            name='roomreview',
            options={'verbose_name': 'room review', 'verbose_name_plural': 'Rooms Reviews'},
        ),
        migrations.AlterModelOptions(
            name='servicereview',
            options={'verbose_name': 'service review', 'verbose_name_plural': 'Services Reviews'},
        ),
        migrations.AlterField(
            model_name='clinicreview',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='entities_details.clinicdetail', verbose_name='clinic'),
        ),
        migrations.AlterField(
            model_name='clinicreview',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='clinicreview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='clinicreview',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='clinicreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_reviews', to='accounts.user', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='entities_details.roomdetail', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_reviews', to='accounts.user', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='review',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='entities_details.servicedetail', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_reviews', to='accounts.user', verbose_name='user'),
        ),
    ]
