# Generated by Django 3.1.5 on 2021-04-05 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20210405_0741'),
        ('entities_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicdetail',
            options={'verbose_name': 'clinic details', 'verbose_name_plural': 'Clinics Details'},
        ),
        migrations.AlterModelOptions(
            name='clinicschedule',
            options={'verbose_name': 'clinic schedule'},
        ),
        migrations.AlterModelOptions(
            name='roomdetail',
            options={'verbose_name': 'room detail', 'verbose_name_plural': 'Rooms Details'},
        ),
        migrations.AlterModelOptions(
            name='roomschedule',
            options={'verbose_name': 'room schedule'},
        ),
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'verbose_name': 'service details', 'verbose_name_plural': 'Services Details'},
        ),
        migrations.AlterModelOptions(
            name='serviceschedule',
            options={'verbose_name': 'service schedule'},
        ),
        migrations.AlterField(
            model_name='clinicdetail',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='entities.clinic', verbose_name='clinic'),
        ),
        migrations.AlterField(
            model_name='clinicdetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_details', to='entities.doctor', verbose_name='doctor'),
        ),
        migrations.AlterField(
            model_name='clinicdetail',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clinics_details', to='entities.hospital', verbose_name='hospital'),
        ),
        migrations.AlterField(
            model_name='clinicdetail',
            name='price',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='clinicdetail',
            name='rating_total',
            field=models.PositiveIntegerField(default=0, verbose_name='rating_total'),
        ),
        migrations.AlterField(
            model_name='clinicdetail',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rating_user'),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='entities_details.clinicdetail', verbose_name='clinic'),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='day',
            field=models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='end',
            field=models.TimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='start',
            field=models.TimeField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms_details', to='entities.hospital', verbose_name='hospital'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='price',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='rating_total',
            field=models.PositiveIntegerField(default=0, verbose_name='rating_total'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rating_user'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='entities.room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='day',
            field=models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='end',
            field=models.TimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='entities_details.roomdetail', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='roomschedule',
            name='start',
            field=models.TimeField(verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services_details', to='entities.hospital', verbose_name='hospital'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='price',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='rating_total',
            field=models.PositiveIntegerField(default=0, verbose_name='rating_total'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rating_user'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='entities.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='day',
            field=models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, verbose_name='day'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='end',
            field=models.TimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='entities_details.servicedetail', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='serviceschedule',
            name='start',
            field=models.TimeField(verbose_name='start'),
        ),
    ]
