# Generated by Django 3.2 on 2021-05-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities_details', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='clinics',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ClinicDetail', to='entities.Clinic', verbose_name='clinics'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ClinicDetail', to='entities.Doctor', verbose_name='doctors'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='services',
            field=models.ManyToManyField(related_name='hospitals', through='entities_details.ServiceDetail', to='entities.Service', verbose_name='services'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='entities.clinic', verbose_name='speciality'),
        ),
    ]
