# Generated by Django 3.2 on 2021-04-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_doctor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/photos/doctors/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/photos/hospitals/', verbose_name='photo'),
        ),
    ]
