# Generated by Django 3.2 on 2021-04-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20210411_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/hospitals/', verbose_name='photo'),
        ),
    ]
