# Generated by Django 3.2 on 2021-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_hospital_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/hospitals/', verbose_name='photo'),
        ),
    ]
