# Generated by Django 3.2 on 2021-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_hospital_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/doctors/', verbose_name='photo'),
        ),
    ]
