# Generated by Django 3.2 on 2021-04-15 13:19

from django.db import migrations, models
import treat_min.entities.models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to=treat_min.entities.models.image_path, verbose_name='photo'),
        ),
    ]
