# Generated by Django 3.2 on 2021-04-21 03:12

from django.db import migrations, models
import treat_min.entities.models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_hospital_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to=treat_min.entities.models.image_update, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to=treat_min.entities.models.image_update, verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to=treat_min.entities.models.image_update, verbose_name='photo'),
        ),
    ]
