# Generated by Django 3.2 on 2021-04-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20210421_0512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name'], 'verbose_name': 'hospital', 'verbose_name_plural': 'Hospitals'},
        ),
    ]
