# Generated by Django 3.2 on 2021-05-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_alter_hospital_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='service',
            name='photo',
        ),
        migrations.AddField(
            model_name='hospital',
            name='area',
            field=models.CharField(default='Cairo', max_length=50, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(default='Nasr City', max_length=50, verbose_name='city'),
        ),
    ]
