# Generated by Django 3.2 on 2021-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20210525_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='area',
            field=models.CharField(max_length=50, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
    ]
