# Generated by Django 3.2 on 2021-05-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtration_models', '0001_initial'),
        ('entities', '0013_auto_20210525_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='area',
            field=models.ForeignKey(default='Area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='filtration_models.area', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.ForeignKey(default='City', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='filtration_models.city', verbose_name='city'),
        ),
    ]
