# Generated by Django 3.2 on 2021-05-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=50, verbose_name='price')),
                ('rating_total', models.PositiveIntegerField(default=0, verbose_name='rating total')),
                ('rating_users', models.PositiveSmallIntegerField(default=0, verbose_name='rating users')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='entities.clinic', verbose_name='clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics_details', to='entities.doctor', verbose_name='doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clinics_details', to='entities.hospital', verbose_name='hospital')),
            ],
            options={
                'verbose_name': 'clinic details',
                'verbose_name_plural': 'Clinics Details',
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(default=50, verbose_name='price')),
                ('rating_total', models.PositiveIntegerField(default=0, verbose_name='rating total')),
                ('rating_users', models.PositiveSmallIntegerField(default=0, verbose_name='rating users')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services_details', to='entities.hospital', verbose_name='hospital')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='details', to='entities.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service details',
                'verbose_name_plural': 'Services Details',
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, verbose_name='day')),
                ('start', models.TimeField(verbose_name='start')),
                ('end', models.TimeField(verbose_name='end')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='entities_details.servicedetail', verbose_name='service')),
            ],
            options={
                'verbose_name': 'service schedule',
            },
        ),
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3, verbose_name='day')),
                ('start', models.TimeField(verbose_name='start')),
                ('end', models.TimeField(verbose_name='end')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='entities_details.clinicdetail', verbose_name='clinic')),
            ],
            options={
                'verbose_name': 'clinic schedule',
            },
        ),
        migrations.AddConstraint(
            model_name='serviceschedule',
            constraint=models.UniqueConstraint(fields=('service', 'day', 'start', 'end'), name='unique_service_schedule'),
        ),
        migrations.AddConstraint(
            model_name='servicedetail',
            constraint=models.UniqueConstraint(fields=('hospital', 'service', 'price'), name='unique_service_detail'),
        ),
        migrations.AddConstraint(
            model_name='clinicschedule',
            constraint=models.UniqueConstraint(fields=('clinic', 'day', 'start', 'end'), name='unique_clinic_schedule'),
        ),
        migrations.AddConstraint(
            model_name='clinicdetail',
            constraint=models.UniqueConstraint(fields=('hospital', 'doctor', 'price'), name='unique_clinic_detail'),
        ),
    ]
