# Generated by Django 3.2 on 2021-04-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomdetail',
            options={'verbose_name': 'room details', 'verbose_name_plural': 'Rooms Details'},
        ),
    ]
