# Generated by Django 3.2 on 2021-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities_details', '0002_alter_roomdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicdetail',
            name='rating_total',
            field=models.PositiveIntegerField(default=0, verbose_name='rating total'),
        ),
        migrations.AlterField(
            model_name='clinicdetail',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rating users'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='rating_total',
            field=models.PositiveIntegerField(default=0, verbose_name='rating total'),
        ),
        migrations.AlterField(
            model_name='roomdetail',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rating users'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='rating_total',
            field=models.PositiveIntegerField(default=0, verbose_name='rating total'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='rating_users',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='rating users'),
        ),
    ]
